### ISSUE TITLE
Add Couchbase 2.0 Support

### ISSUE THREAD

**Issue by jabberfest** [ianwhite/orm_adapter#25]
Couchbase 2.0 now supports indexing. It also scales better then MongoDB because MongoDB currently has database wide locks.

In the future it will still have collection wide locks.

I will try to work on a Couchbase adapter, but may not have enough time :-(

**Comment by joraff** [comment]
I took a stab at making an adapter this weekend, but it's going to be difficult to implement since couchbase doesn't have a query language. I may be wrong, but you'll probably need to know beforehand which fields either you or the gem you want to use needs to perform queries on to create either helper documents or views.

Either that or create views on demand, but since performance degrades with more views in the design document I'm not sure this is a good idea.

@scalabl3

**Comment by yangtheman** [comment]
Piggybacking on this, is this the same reason why couchrest is not supported? I was actually working on creating the adapter, and about 10 test cases of example_app_shared were failing due to how couchrest behaves (default ordering by ID instead of created_time). In order to make the tests pass, couchrest would have to be modified. 

So, my follow-up question is, does an adapter need to pass all the tests in example_app_shared before being merged? 

Thanks!

**Comment by josevalim** [comment]
We recommend ORMs to implement their adapters as a separate gem, as havin
everything inside this gem would get unmanageable. :) thanks for your work
anyway!


## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by jabberfest** [comment]
I was a little bit confused. Couchbase has it's own ORM called couchbase-ruby-model which is a gem.

We would need to just create an adapter in lib/orm_adapter/adapters/couchbase.rb

The issue is still that couchbase-ruby-model doesn't have a query language. I was told by some engineers at couchbase that ~December when couchbase 3.0 comes out they will have a query language.

It should make more sense to write an adapter then.

**Comment by farias-r7** [comment]
@joraff Looks like this should be possible now. See

http://www.couchbase.com/communities/n1ql

They added a SQL like query language to couchbase. It is in developer preview.

**Comment by sideshowcoder** [comment]
I took a stab at this and came up with https://github.com/sideshowcoder/orm_adapter-couchbase it was mainly just me wanting to see how something like this could work leveraging views where possible, but having all the functionality there even when it can't be done via views. I don't think the n1ql is necessary to support this kind of functionality as we have most of the parts available right now via views already. There are a couple things left todo especially around the hacky patches to couchbase-ruby-model as well as making more use of views for conditons but at least it passes the tests for now.

Thought I just leave this here if anybody is interested.

**Comment by ianwhite** [comment]
Thanks @sideshowcoder for the adapter.  As @josevalim has said, we encourage adapters to be implemented in separate repos.

Here's a list btw: https://rubygems.org/search?query=orm_adapter- (I should link to this in the README)
